### ISSUE TITLE
succeed run but has warnning ，and not  alarm and behavior 

### ISSUE THREAD

**Issue by blackorbird** [0x71/cuckoo-linux#4]
2016-12-16 14:55:16,782 [lib.cuckoo.common.netlog] WARNING: Got API with unknown index - monitor needs to explain first: {u'I': -1, u'args': [1, u'0', u'0x00000000f7760020', u'0x0000000000000000', u'0x00000000f770bff4', u'0x0000000000000000', u'0x0000000000000000', u'0x0000000000000000'], u'T': 8599, u't': 0.40495991706848145}

**Comment by 0x71** [comment]
@shiyelin could you please submit the agent log that is generated in the guest machine?

**Comment by blackorbird** [comment]
@0x71 
![thankyou](https://cloud.githubusercontent.com/assets/14833213/21380479/814869a0-c790-11e6-97bc-abf0214ae652.png)

**Comment by blackorbird** [comment]
@0x71 my email is 137812951@qq.com ,something i need to ask you ......

there has some error i can't deal it...help
there is the log:
2016-12-16 14:52:30,114 [root] DEBUG: Sending: {'I': 33, 'args': [0, '-2 ENOENT (No such file or directory)', u'4', u'4151505396'], 'T': 8564, 't': 0.06487703323364258}
2016-12-16 14:52:30,115 [root] ERROR: Format argument path of function lgetxattr() value error: [ProcessError] readBytes(0x00000000ffffffff, 256) error: [Errno 5] Input/output error
2016-12-16 14:52:30,116 [root] WARNING: Traceback (most recent call last):
2016-12-16 14:52:30,116 [root] WARNING:   File "/usr/local/lib/python2.7/dist-packages/python_ptrace-0.9.1-py2.7.egg/ptrace/func_arg.py", line 33, in getText
2016-12-16 14:52:30,117 [root] WARNING:     text = self.createText()
2016-12-16 14:52:30,117 [root] WARNING:   File "/usr/local/lib/python2.7/dist-packages/python_ptrace-0.9.1-py2.7.egg/ptrace/syscall/syscall_argument.py", line 123, in createText
2016-12-16 14:52:30,117 [root] WARNING:     return self.readCString(value)
2016-12-16 14:52:30,117 [root] WARNING:   File "/usr/local/lib/python2.7/dist-packages/python_ptrace-0.9.1-py2.7.egg/ptrace/syscall/syscall_argument.py", line 200, in readCString
2016-12-16 14:52:30,117 [root] WARNING:     address, max_size)
2016-12-16 14:52:30,117 [root] WARNING:   File "/usr/local/lib/python2.7/dist-packages/python_ptrace-0.9.1-py2.7.egg/ptrace/debugger/process.py", line 661, in readCString
2016-12-16 14:52:30,117 [root] WARNING:     data = self.readBytes(address, chunk_length)
2016-12-16 14:52:30,118 [root] WARNING:   File "/usr/local/lib/python2.7/dist-packages/python_ptrace-0.9.1-py2.7.egg/ptrace/debugger/process.py", line 577, in readBytes
2016-12-16 14:52:30,118 [root] WARNING:     formatAddress(address), size, err))
2016-12-16 14:52:30,118 [root] WARNING: ProcessError: readBytes(0x00000000ffffffff, 256) error: [Errno 5] Input/output error
2016-12-16 14:52:30,145 [root] DEBUG: Sending: {'I': 192, 'category': 'unkown', 'args': ['is_success', 'retval', u'path', u'name', u'value', u'size'], 'type': 'info', 'name': 'lgetxattr'}
2016-12-16 14:52:30,146 [root] DEBUG: Sending: {'I': 192, 'args': [1, u'4151500800 (0x00000000f772e000)', u'4294967295L', u'0x0000000000000022', u'0x0000000000000003', u'0'], 'T': 8564, 't': 0.09627699851989746}
2016-12-16 14:52:30,146 [root] DEBUG: Sending: {'I': 33, 'args': [0, '-2 ENOENT (No such file or directory)', u'4151647252', u'4151614828'], 'T': 8564, 't': 0.09689188003540039}
2016-12-16 14:52:30,147 [root] DEBUG: Sending: {'I': 5, 'category': 'filesystem', 'args': ['is_success', 'retval', u'fd', u'statbuf'], 'type': 'info', 'name': 'fstat'}
2016-12-16 14:52:30,147 [root] DEBUG: Sending: {'I': 5, 'args': [1, '3', u'4151646976', u'0x00000000f775189c'], 'T': 8564, 't': 0.09736895561218262}
2016-12-16 14:52:30,147 [root] ERROR: Format argument path of function removexattr() value error: [ProcessError] readBytes(0x0000000000000003, 256) error: [Errno 5] Input/output error
2016-12-16 14:52:30,147 [root] WARNING: Traceback (most recent call last):
2016-12-16 14:52:30,147 [root] WARNING:   File "/usr/local/lib/python2.7/dist-packages/python_ptrace-0.9.1-py2.7.egg/ptrace/func_arg.py", line 33, in getText
2016-12-16 14:52:30,147 [root] WARNING:     text = self.createText()
2016-12-16 14:52:30,147 [root] WARNING:   File "/usr/local/lib/python2.7/dist-packages/python_ptrace-0.9.1-py2.7.egg/ptrace/syscall/syscall_argument.py", line 123, in createText
2016-12-16 14:52:30,148 [root] WARNING:     return self.readCString(value)
2016-12-16 14:52:30,148 [root] WARNING:   File "/usr/local/lib/python2.7/dist-packages/python_ptrace-0.9.1-py2.7.egg/ptrace/syscall/syscall_argument.py", line 200, in readCString
2016-12-16 14:52:30,148 [root] WARNING:     address, max_size)
2016-12-16 14:52:30,148 [root] WARNING:   File "/usr/local/lib/python2.7/dist-packages/python_ptrace-0.9.1-py2.7.egg/ptrace/debugger/process.py", line 661, in readCString
2016-12-16 14:52:30,148 [root] WARNING:     data = self.readBytes(address, chunk_length)
2016-12-16 14:52:30,148 [root] WARNING:   File "/usr/local/lib/python2.7/dist-packages/python_ptrace-0.9.1-py2.7.egg/ptrace/debugger/process.py", line 577, in readBytes
2016-12-16 14:52:30,148 [root] WARNING:     formatAddress(address), size, err))
2016-12-16 14:52:30,148 [root] WARNING: ProcessError: readBytes(0x0000000000000003, 256) error: [Errno 5] Input/output error
2016-12-16 14:52:30,148 [root] DEBUG: Sending: {'I': 197, 'category': 'unkown', 'args': ['is_success', 'retval', u'path', u'name'], 'type': 'info', 'name': 'removexattr'}
2016-12-16 14:52:30,148 [root] DEBUG: Sending: {'I': 197, 'args': [1, '0', u'3L', u'0x00000000f775189c'], 'T': 8564, 't': 0.09880495071411133}
2016-12-16 14:52:30,188 [root] ERROR: Format argument path of function lgetxattr() value error: [ProcessError] readBytes(0x0000000000000003, 256) error: [Errno 5] Input/output error
2016-12-16 14:52:30,189 [root] WARNING: Traceback (most recent call last):
2016-12-16 14:52:30,189 [root] WARNING:   File "/usr/local/lib/python2.7/dist-packages/python_ptrace-0.9.1-py2.7.egg/ptrace/func_arg.py", line 33, in getText
2016-12-16 14:52:30,189 [root] WARNING:     text = self.createText()
2016-12-16 14:52:30,189 [root] WARNING:   File "/usr/local/lib/python2.7/dist-packages/python_ptrace-0.9.1-py2.7.egg/ptrace/syscall/syscall_argument.py", line 123, in createText
2016-12-16 14:52:30,189 [root] WARNING:     return self.readCString(value)
2016-12-16 14:52:30,189 [root] WARNING:   File "/usr/local/lib/python2.7/dist-packages/python_ptrace-0.9.1-py2.7.egg/ptrace/syscall/syscall_argument.py", line 200, in readCString
2016-12-16 14:52:30,189 [root] WARNING:     address, max_size)
2016-12-16 14:52:30,189 [root] WARNING:   File "/usr/local/lib/python2.7/dist-packages/python_ptrace-0.9.1-py2.7.egg/ptrace/debugger/process.py", line 661, in readCString
2016-12-16 14:52:30,189 [root] WARNING:     data = self.readBytes(address, chunk_length)
2016-12-16 14:52:30,189 [root] WARNING:   File "/usr/local/lib/python2.7/dist-packages/python_ptrace-0.9.1-py2.7.egg/ptrace/debugger/process.py", line 577, in readBytes
2016-12-16 14:52:30,189 [root] WARNING:     formatAddress(address), size, err))
2016-12-16 14:52:30,189 [root] WARNING: ProcessError: readBytes(0x0000000000000003, 256) error: [Errno 5] Input/output error
2016-12-16 14:52:30,190 [root] DEBUG: Sending: {'I': 192, 'args': [1, u'4151431168 (0x00000000f771d000)', u'3L', u'0x0000000000000002', u'0x0000000000000001', u'0'], 'T': 8564, 't': 0.14017581939697266}
2016-12-16 14:52:30,190 [root] ERROR: Format argument filename of function lstat() value error: [ProcessError] readBytes(0x0000000000000003, 256) error: [Errno 5] Input/output error
2016-12-16 14:52:30,190 [root] WARNING: Traceback (most recent call last):
2016-12-16 14:52:30,190 [root] WARNING:   File "/usr/local/lib/python2.7/dist-packages/python_ptrace-0.9.1-py2.7.egg/ptrace/func_arg.py", line 33, in getText
2016-12-16 14:52:30,190 [root] WARNING:     text = self.createText()
2016-12-16 14:52:30,190 [root] WARNING:   File "/usr/local/lib/python2.7/dist-packages/python_ptrace-0.9.1-py2.7.egg/ptrace/syscall/syscall_argument.py", line 123, in createText
2016-12-16 14:52:30,190 [root] WARNING:     return self.readCString(value)
2016-12-16 14:52:30,194 [root] WARNING:   File "/usr/local/lib/python2.7/dist-packages/python_ptrace-0.9.1-py2.7.egg/ptrace/syscall/syscall_argument.py", line 200, in readCString
2016-12-16 14:52:30,194 [root] WARNING:     address, max_size)
2016-12-16 14:52:30,195 [root] WARNING:   File "/usr/local/lib/python2.7/dist-packages/python_ptrace-0.9.1-py2.7.egg/ptrace/debugger/process.py", line 661, in readCString
2016-12-16 14:52:30,195 [root] WARNING:     data = self.readBytes(address, chunk_length)
2016-12-16 14:52:30,195 [root] WARNING:   File "/usr/local/lib/python2.7/dist-packages/python_ptrace-0.9.1-py2.7.egg/ptrace/debugger/process.py", line 577, in readBytes
2016-12-16 14:52:30,195 [root] WARNING:     formatAddress(address), size, err))
2016-12-16 14:52:30,195 [root] WARNING: ProcessError: readBytes(0x0000000000000003, 256) error: [Errno 5] Input/output error
2016-12-16 14:52:30,195 [root] DEBUG: Sending: {'I': 6, 'category': 'filesystem', 'args': ['is_success', 'retval', u'filename', u'statbuf'], 'type': 'info', 'name': 'lstat'}
2016-12-16 14:52:30,195 [root] DEBUG: Sending: {'I': 6, 'args': [1, '0', u'3L', u'0x00000000f775189c'], 'T': 8564, 't': 0.14557099342346191}
2016-12-16 14:52:30,195 [root] DEBUG: Sending: {'I': 33, 'args': [0, '-2 ENOENT (No such file or directory)', u'4151643643', u'4291155691'], 'T': 8564, 't': 0.14582586288452148}
2016-12-16 14:52:30,196 [root] DEBUG: Sending: {'I': 5, 'args': [1, '3', u'4151646976', u'0x0000000000000008'], 'T': 8564, 't': 0.14613890647888184}
2016-12-16 14:52:30,196 [root] DEBUG: Sending: {'I': 3, 'category': 'filesystem', 'args': ['is_success', 'retval', u'fd'], 'type': 'info', 'name': 'close'}
2016-12-16 14:52:30,196 [root] DEBUG: Sending: {'I': 3, 'args': [1, u'512 (0x0000000000000200)', u'4291153716'], 'T': 8564, 't': 0.14649701118469238}
2016-12-16 14:52:30,196 [root] DEBUG: Sending: {'I': 197, 'args': [1, '0', u"'\\xff\\xff\\xff\\xff'", u'0x000000000804884d'], 'T': 8564, 't': 0.1467759609222412}
2016-12-16 14:52:30,198 [root] ERROR: Format argument path of function lgetxattr() value error: [ProcessError] readBytes(0x00000000ffffffff, 256) error: [Errno 5] Input/output error
2016-12-16 14:52:30,214 [root] WARNING: Traceback (most recent call last):
